sudo: required
services:
  - docker
env:
  - IMAGE_NAME=andrelmlins/freesoccer
install: []
before_script:
  - docker pull "${IMAGE_NAME}:latest" || true
script:
  - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
