declare module 'cheerio';
declare module 'morgan';
declare module 'md5';
declare module 'swagger-ui-express';
declare module 'cron';
declare module 'jsonwebtoken';
declare module 'bcrypt';
declare module 'puppeteer';
declare module 'serve-favicon';
